name: Deploy
on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/setup@v2.0.2
        with:
          cache: true
      - run: pnpm check
      - run: pnpm build
      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          folder: dist
